language: node_js
node_js:
    - "stable"
dist: trusty
sudo: required
before_install:
    - export DISPLAY=:99.0
    - sh -e /etc/init.d/xvfb start
    - npm install -g codecov
before_script:
    - npm i -g typescript@latest
    - npm run-script lint
script:
    - npm run-script bundle
    - npm run-script test:all
post_script:
    - npm run-script coverage
    - npm run-script docs
after_success:
    - codecov
branches:
    only:
    - master
    - develop
deploy:
    provider: pages
    skip-cleanup: true
    github-token: $GITHUB_TOKEN
    keep-history: true
    script:
        - npx semantic-release
    on:
        branch: master
notifications:
    email:
        on_success: change
        on_failure: change 
git:
    depth: 1

