language: node_js
node_js:
    - "stable"
dist: trusty
sudo: required
before_install:
    - export DISPLAY=:99.0
    - sh -e /etc/init.d/xvfb start
before_script:
    - npm install -g codecov
    - npm install
script:
    - npm run-script test:all
after_success:
    - npm run-script docs
branches:
    only:
    - master
deploy:
    provider: pages
    skip-cleanup: true
    github-token: $GITHUB_TOKEN
    keep-history: true
    script:
        - npx semantic-release
    on:
        branch: master
notifications:
    email:
        on_success: change
        on_failure: change 
git:
    depth: 1
