name: Node.js CI/CD

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
      - feature/*
      - hotfix/*

jobs:
  build:
    name: Build on node ${{ matrix.node_version }} and ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        node_version:
          - 12
        os: 
          - macOS-latest
          - ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@master
        with:
          submodules: true
      - name: Use Node.js ${{ matrix.node_version }}
        uses: actions/setup-node@master
        with:
          version: ${{ matrix.node_version }}
      - run: |
          npm install
          npm run bundle

  test:
    name: Test on node ${{ matrix.node_version }} and ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        node_version:
          - 12
        os: 
          - macOS-latest
          - ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@master
      - name: Use Node.js ${{ matrix.node_version }}
        uses: actions/setup-node@master
        with:
          version: ${{ matrix.node_version }}
      - run: |
          npm install
          npm run test
  
  coverage:
    needs: [build, test]
    name: Run coverage on Coveralls
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@master
      - uses: actions/setup-node@master
        with:
          version: 12
      - name: Install codecov
        run: |
          npm install -g codecov
          npm install
          npm run test:all
      - name: Coveralls
        uses: coverallsapp/github-action@master
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}

  docs:
    needs: [build, test]
    name: Builds and deploys documentation
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@master
      - uses: actions/setup-node@master
        with:
          version: 12
      - name: Build Documentation
        run: |
          npm install
          npm run docs

  gh_pages:
    needs: [build, test, docs]
    name: Deploys the README to GitHub Pages
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@master
      - uses: actions/setup-node@master
        with:
          version: 12
      - name: GitHub Pages Deploy
        uses: maxheld83/ghpages@master
        env:
          BUILD_DIR: "."
          GH_PAT: ${{secrets.GITHUB_TOKEN}}

  publish_npm:
    needs: [build, test, coverage, docs]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Update package version
        run: |
          npm install --save-dev semantic-release
          npm run semantic-release
      - uses: actions/setup-node@v1
        with: 
          version: 12
          registry-url: "https://registry.npmjs.org/"
      - run: npm install
      - run: npm publish
        if: github.event == 'push'
        env:
          NODE_AUTH_TOKEN: ${{ secrets.npm_token }}

  publish_gh:
    needs: [build, test, coverage, docs]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-node@v1
        with:
          node-version: 12
          registry-url: "https://npm.pkg.github.com/"
          scope: '@srepollock'
          always-auth: true
      - run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}